my_site/api_loan/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

app_name = 'api_loan'

router = routers.DefaultRouter()
router.register("api_loan", views.ApprovalsView)
urlpatterns = [
    # path('api/', include(router.urls)),
    # path('status/', views.approvereject),
    path('loan/', views.cxcontact, name="cxform")
]

my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume.urls')),
    path('api/', include('api_loan.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/resume/urls.py
from django.urls import path, include
from .views import HomeTemplateView

app_name = 'resume'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
]

my_site/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Aznor Yusof's Personal Portfolio</title>
    {% include 'includes/stylesheets.html' %}
</head>
<body>

<div class="loader_bg">
    <div class="loader"></div>
</div>

<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/">Résumé<span>.</span> </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a class="smooth-menu" href="#home">Home</a></li>
                <li><a class="smooth-menu" href="#about">About</a></li>
                <li><a class="smooth-menu" href="#services">Services</a></li>
                <li><a class="smooth-menu" href="#portfolio">Portfolio</a></li>
                <!-- <li><a class="smooth-menu" href="#testimonial">Testimonial</a></li> -->
                <li><a class="smooth-menu" href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<div class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <p>&copy;Copyright 2020</p>
                <p>Website template created by Manjurul Hoque</p>
            </div>
        </div>
    </div>
</div>
{% include 'includes/scripts.html' %}
</body>
</html>

my_site/templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div id="home" class="banner-area section-padding">
        <div class="bg-overlay black"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="welcome-text">
                        <div class="name-area wow fadeInDown" data-wow-delay="0.2s">Hello, I am Aznor</div>
                        <h1 class="wow fadeInDown" data-wow-delay="0.4s">Data Scientist developing ML tools</h1>
                        <a href="#about" class="my-btn-1 wow fadeInDown" data-wow-delay="0.6s">Learn more</a>
                        <a href="#contact" class="my-btn-2 wow fadeInDown" data-wow-delay="0.8s">Get in touch</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    About section#}

    <div id="about" class="about-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-sn-8 col-xs-12 wow fadeInLeft" data-wow-delay="0.2s">
                    <div class="about-left">
                        <h2 class="section-title">About Me</h2>
                        <div class="line"></div>
                        <h4>{{ about.short_description }}</h4>
                        <p>{{ about.description }}</p>
                        <a href="{{ about.cv.url }}" download>Download CV&nbsp;<i class="fa fa-download"></i></a>
                    </div>
                </div>
                <div class="col-md-5 visible-md visible-lg wow fadeInDown" data-wow-delay="0.6s">
                    <div class="profile">
                        <img src="{{ about.image.url }}" alt="Profile image" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    Services Section#}
    <div id="services" class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header text-center">
                        <h2>Services I offer</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for service in services %}
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                        <div class="single-service wow fadeInDown" data-wow-delay="0.2s">
                            <i class="material-icons">insights</i>
                            <h2>{{ service.name }}</h2>
                            <p>{{ service.description }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {#    Recent Works Section#}
    <div id="portfolio" class="portfolio-area section-padding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header">
                        <h2>My Recent Works</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for work in works %}
                    <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
                        <div class="gallery-items">
                            <a class="link to another api page" href="{% url 'api_loan:cxform' %}">
                                <img src="{{ work.image.url }}" alt="work image">
                            </a>
                            <div class="gallery-text">
                                <h2>{{ work.title }}</h2>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {#    Contact section#}

    <div class="invitation-area section-padding">
        <div class="container">
            <div class="row">
                <div class="single-invite text-center">
                    <h2>Do you have any projects that needs to be done?</h2>
                    <p></p>
                    <a href="#contact" class="my-btn-3">Get started</a>
                </div>
            </div>
        </div>
    </div>

    <div id="contact" class="contact-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-header text-center">
                        <h2>Contact Me</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 box-contact-form">

                    <form id="contact-form" method="post" action="#">

                        <div class="messages"></div>

                        <div class="controls">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group wow fadeInDown" data-wow-delay="0.2s">
                                        <input id="form_name" type="text" name="name" class="form-control"
                                               placeholder="Enter your full name *" required="required"
                                               data-error="Fullname is required.">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group wow fadeInDown" data-wow-delay="0.4s">
                                        <input id="form_email" type="email" name="email" class="form-control"
                                               placeholder="Enter your email *" required="required"
                                               data-error="Valid email is required.">
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group wow fadeInUp" data-wow-delay="0.6s">
                                        <textarea id="form_message" name="message" class="form-control"
                                                  placeholder="Your Message *" rows="4" required="required"
                                                  data-error="Leave a message for me"></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button class="btn btn-send" value="">Send message</button>
                                </div>
                            </div>
                        </div>

                    </form>

                </div>

            </div>
        </div>
    </div>

{% endblock %}